<script setup>
import { ArrowRight, Check, Van, TrendCharts, Timer, Switch, Lock } from '@element-plus/icons-vue'
import { useRouter } from 'vue-router'
import { trackEvent } from '../utils/analytics.js'
const router=useRouter()
const tools=[['logistics-quote',Van,'物流成本报价','成本、损耗、税费、利润率与阶梯运费一次算清。'],['irr',TrendCharts,'真实 IRR','看清分期背后的真实年化资金成本。'],['workdays',Timer,'工时工作日','班次工时、加班与排除周末的工作日统计。'],['unit-converter',Switch,'物流单位换算','重量、体积、CBM 和材积快捷换算。']]
function go(path,event){trackEvent(event);router.push(path)}
</script>
<template><div class="landing"><header class="landing-nav"><router-link to="/" class="landing-brand"><img src="/favicon.png" alt="链算 Pro"/>链算 Pro</router-link><div><el-button text @click="go('/login','login_click')">登录</el-button><el-button type="primary" @click="go('/register','register_click')">免费开始</el-button></div></header><main><section class="landing-hero"><p>LOGISTICS BUSINESS TOOLKIT</p><h1>物流报价算得准，<em>每单利润看得清。</em></h1><div class="landing-lead">面向物流供应链和小商户的商业计算工具。基础功能免费，计算数据优先保存在你的浏览器。</div><div class="landing-cta"><el-button type="primary" size="large" :icon="ArrowRight" @click="go('/tools/logistics-quote','hero_quote_click')">免费试算物流报价</el-button><el-button size="large" @click="go('/register','hero_register_click')">创建免费账户</el-button></div><div class="trust-line"><span>✓ 无需安装</span><span>✓ 本地优先</span><span>✓ 手机电脑都能用</span></div></section><section class="landing-section"><div class="section-copy"><p>常用工具</p><h2>先算一笔，再决定要不要注册。</h2></div><div class="tool-grid"><button v-for="tool in tools" :key="tool[0]" class="tool-preview" @click="go('/tools/'+tool[0],'tool_preview_click')"><el-icon><component :is="tool[1]"/></el-icon><h3>{{ tool[2] }}</h3><p>{{ tool[3] }}</p><span>立即试算 <ArrowRight /></span></button></div></section><section class="landing-section benefits"><div><p>PRO 会员</p><h2>同一套完整权益，按月或按年灵活续费。</h2><p class="muted">月度与年度会员功能完全一致；年度会员约省 18%，折合 ¥23.75/月。</p></div><ul><li><Check/> Excel 批量导出</li><li><Check/> 保存自定义公式</li><li><Check/> AI 自然语言计算</li><li><Check/> 付款凭证人工审核</li></ul><el-button type="primary" @click="go('/upgrade','landing_upgrade_click')"><Lock/> 查看会员方案</el-button></section><section class="landing-section faq"><div class="section-copy"><p>常见问题</p><h2>把关键信息说清楚。</h2></div><el-collapse><el-collapse-item title="我的计算数据会上传吗？" name="1">基础计算记录、模板和主题偏好优先保存在当前浏览器。AI 计算仅在你主动提交问题时发送到 AI 服务。</el-collapse-item><el-collapse-item title="付款后多久开通？" name="2">上传付款凭证后，管理员会核对真实到账记录；通过后自动开通会员。</el-collapse-item><el-collapse-item title="会员到期后会怎样？" name="3">高级功能会自动重新锁定。提前续费会从当前到期日继续顺延。</el-collapse-item></el-collapse></section></main><footer>链算 Pro · <router-link to="/contact">联系我们</router-link> · <router-link to="/privacy">隐私说明</router-link></footer></div></template>
<style scoped>.landing{min-height:100vh;background:radial-gradient(circle at 85% 0,rgba(25,148,121,.12),transparent 32%),var(--card)}.landing-nav{height:72px;max-width:1120px;margin:auto;padding:0 24px;display:flex;align-items:center;justify-content:space-between}.landing-brand{display:flex;align-items:center;gap:10px;font-weight:800;color:inherit;text-decoration:none}.landing-brand img{width:34px;height:34px;border-radius:9px}.landing-hero,.landing-section{max-width:1120px;margin:auto;padding:72px 24px}.landing-hero{text-align:center;max-width:900px}.landing-hero>p,.section-copy>p,.benefits>div>p:first-child{color:var(--brand);font-weight:800;font-size:12px;letter-spacing:.14em}.landing-hero h1{font-size:clamp(38px,6vw,68px);letter-spacing:-.06em;line-height:1.04;margin:14px 0}.landing-hero em{font-style:normal;color:var(--brand)}.landing-lead,.muted{color:var(--muted);font-size:17px;line-height:1.8}.landing-cta{display:flex;justify-content:center;gap:12px;margin:28px 0}.trust-line{display:flex;justify-content:center;gap:18px;color:var(--muted);font-size:13px}.landing-section{padding-top:38px}.section-copy h2,.benefits h2{font-size:32px;margin:8px 0 26px}.tool-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.tool-preview{border:1px solid var(--line);background:var(--card);border-radius:16px;padding:22px;text-align:left;color:inherit;cursor:pointer}.tool-preview:hover{border-color:var(--brand);transform:translateY(-3px)}.tool-preview .el-icon{color:var(--brand);font-size:24px}.tool-preview h3{margin:16px 0 8px}.tool-preview p{color:var(--muted);line-height:1.6;font-size:14px}.tool-preview span{color:var(--brand);display:flex;gap:4px;align-items:center;font-size:13px;font-weight:700}.benefits{display:grid;grid-template-columns:1.4fr 1fr auto;align-items:center;gap:28px;background:color-mix(in srgb,var(--brand-soft) 65%,var(--card));border-radius:22px;margin-top:40px}.benefits h2{margin-bottom:8px}.benefits ul{list-style:none;padding:0;line-height:2.2}.benefits li{display:flex;gap:8px;align-items:center}.benefits li svg{color:var(--brand)}.faq{max-width:800px}.faq :deep(.el-collapse-item__header){font-size:16px}footer{text-align:center;padding:42px;color:var(--muted);font-size:13px}footer a{color:var(--brand);text-decoration:none}@media(max-width:760px){.tool-grid,.benefits{grid-template-columns:1fr}.landing-hero,.landing-section{padding:48px 18px}.landing-cta,.trust-line{flex-wrap:wrap}.landing-cta .el-button{width:100%}}</style>
