<script setup>
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft, Lock } from '@element-plus/icons-vue'
import LogisticsCalculator from '../components/LogisticsCalculator.vue'
import IrrCalculator from '../components/IrrCalculator.vue'
import WorkdayCalculator from '../components/WorkdayCalculator.vue'
import UnitConverter from '../components/UnitConverter.vue'
import { trackEvent } from '../utils/analytics.js'
const route=useRoute(),router=useRouter()
const data={'logistics-quote':['物流成本报价计算器','输入采购、运费、损耗、税率与目标利润，得到可执行的建议报价。',LogisticsCalculator],irr:['真实 IRR 分期计算器','用真实现金流计算月度 IRR、名义年利率与实际年化利率。',IrrCalculator],workdays:['工时与工作日计算器','计算实际工作时长、加班时长以及排除周末后的工作日。',WorkdayCalculator],'unit-converter':['物流单位换算','重量、体积、CBM 和材积换算，适配物流日常业务。',UnitConverter]}
const tool=computed(()=>data[route.params.slug]||data['logistics-quote'])
function login(){trackEvent('tool_login_click',{tool:route.params.slug});router.push({path:'/login',query:{entry:'landing'}})}
function register(){trackEvent('save_quote_click',{tool:route.params.slug});router.push('/register')}
</script>
<template><div class="public-tool"><header><router-link to="/"><ArrowLeft/> 返回首页</router-link><el-button type="primary" @click="login">登录后保存数据</el-button></header><main><p>免费工具</p><h1>{{ tool[0] }}</h1><div class="tool-desc">{{ tool[1] }}</div><section class="public-tool-card"><component :is="tool[2]"/></section><aside><el-icon class="access-lock" :size="18"><Lock/></el-icon><span>这份报价已算好。登录后可保存本次报价、下次一键复用，并导出 Excel 报价单</span><el-button link type="primary" @click="register">保存这份报价</el-button></aside></main></div></template>
<style scoped>.public-tool{min-height:100vh;background:radial-gradient(circle at 88% 5%,rgba(15,148,136,.12),transparent 28%),radial-gradient(circle at 10% 0,rgba(23,105,213,.1),transparent 30%),var(--surface);overflow:hidden}.dark .public-tool{background:radial-gradient(circle at 88% 5%,rgba(79,196,168,.12),transparent 31%)}.public-tool header{height:68px;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:0 max(20px,calc((100% - 1120px)/2));background:color-mix(in srgb,var(--card) 90%,transparent);border-bottom:1px solid var(--line);backdrop-filter:blur(14px)}.public-tool header a{display:flex;align-items:center;gap:5px;flex:0 0 auto;min-width:max-content;white-space:nowrap;text-decoration:none;color:var(--muted);font-weight:700;font-size:14px}.public-tool header .el-button{flex:0 1 auto;white-space:nowrap}.public-tool main{max-width:1040px;margin:auto;padding:56px 20px}.public-tool main>p{margin:0;color:var(--brand);font-weight:800;font-size:12px;letter-spacing:.12em}.public-tool h1{font-size:38px;letter-spacing:-.04em;margin:10px 0}.tool-desc{max-width:620px;color:var(--muted);line-height:1.8;margin-bottom:30px}.public-tool-card{background:var(--card);border:1px solid var(--line);border-radius:22px;padding:30px;box-shadow:0 18px 38px rgba(25,47,89,.075)}.public-tool aside{margin-top:16px;display:flex;align-items:center;gap:10px;background:linear-gradient(115deg,#eef6ff,#f4fbfa);border:1px solid #c9e1da;padding:15px 17px;border-radius:14px;color:var(--muted);font-size:13px;line-height:1.65}.public-tool aside .access-lock{color:var(--brand);flex:none}@media(max-width:600px){.public-tool header{padding:0 12px}.public-tool header .el-button{padding-inline:10px;font-size:12px}.public-tool main{padding:38px 12px}.public-tool h1{font-size:31px}.public-tool-card{padding:18px 12px}.public-tool aside{align-items:flex-start;flex-wrap:wrap}}</style>
