<script setup>
import { computed, ref } from 'vue'
import { Plus, Delete } from '@element-plus/icons-vue'
import { money } from '../utils/storage'
import ResultBox from './ResultBox.vue'
import { calculateLogisticsQuote, resolveTierFee } from '../lib/calculations.js'
const form=ref({purchase:1000,freight:120,packing:18,loss:2,tax:6,profit:16,weight:0})
const tiers=ref([{min:0,max:10,fee:12},{min:10,max:50,fee:45},{min:50,max:100,fee:80}])
const tierFreight=computed(()=>resolveTierFee(Number(form.value.weight), tiers.value))
const calc=computed(()=>calculateLogisticsQuote(form.value, tiers.value))
</script>
<template><div><div class="section-heading"><div><span>02 · LOGISTICS QUOTE</span><h2>物流成本报价</h2><p>把隐性成本摊开算，报价才不吃暗亏。</p></div><el-tag type="success" effect="light">核心功能</el-tag></div><div class="two-column"><div><h3>成本参数</h3><el-form label-position="top" class="form-grid"><el-form-item label="进货成本（元）"><el-input-number v-model="form.purchase" :min="0" :precision="2" controls-position="right"/></el-form-item><el-form-item label="基础运费（元）"><el-input-number v-model="form.freight" :min="0" :precision="2" controls-position="right"/></el-form-item><el-form-item label="包装费（元）"><el-input-number v-model="form.packing" :min="0" :precision="2" controls-position="right"/></el-form-item><el-form-item label="货物重量（kg）"><el-input-number v-model="form.weight" :min="0" :precision="2" controls-position="right"/></el-form-item><el-form-item label="损耗率（%）"><el-input-number v-model="form.loss" :min="0" :max="100"/></el-form-item><el-form-item label="增值税率（%）"><el-input-number v-model="form.tax" :min="0" :max="100"/></el-form-item><el-form-item label="目标利润率（%）"><el-input-number v-model="form.profit" :min="0" :max="99"/></el-form-item></el-form><div class="tier-panel"><div class="aside-title"><strong>阶梯分段运费</strong><el-button text :icon="Plus" @click="tiers.push({min:0,max:0,fee:0})">添加区间</el-button></div><div v-for="(tier,i) in tiers" :key="i" class="tier-row"><el-input-number v-model="tier.min" :min="0" size="small"/><span>至</span><el-input-number v-model="tier.max" :min="0" size="small"/><span>kg / ¥</span><el-input-number v-model="tier.fee" :min="0" size="small"/><el-button text :icon="Delete" @click="tiers.splice(i,1)"/></div><p>当前阶梯运费：¥ {{ money(tierFreight) }}</p></div></div><div class="result-panel"><span class="panel-kicker">实时报价结果</span><ResultBox label="建议对外报价" :value="`¥ ${money(calc.quote)}`" featured/><ResultBox label="总成本" :value="`¥ ${money(calc.total)}`"/><ResultBox label="税费" :value="`¥ ${money(calc.tax)}`"/><ResultBox label="毛利" :value="`¥ ${money(calc.gross)}`"/><ResultBox label="毛利率" :value="`${calc.rate.toFixed(2)}%`"/><p class="formula-note">报价 =（进货 + 运费 + 包装 + 损耗 + 税费）÷（1 - 目标利润率）</p></div></div></div></template>
